### PR TITLE
Improved algorithm reaching 32k tile

### PR DESCRIPTION
**Pull request by xificurk**
This PR improves the algorithm, so that it consistently reaches 32k tile. Here (https://www.dropbox.com/s/9463l6ztznj3zy0/2048.png) is a "Game over" screenshot of one of the best games I've seen it play.

First there are couple of minor code tweaks. I have also moved caching and search termination code to `score_tilechoose_node` method. Imho, it makes more sense to use it after player's deterministic move, instead of after random computer move, although the benchmarking I tried did not show significant improvements. The two most important commits are **new heuristic scoring** and **adaptive search depth limit**.

**New heuristic scoring**

It uses a combination of three factors - number of empty tiles, number of available merge moves and monotonicity of the row/column.
An empty tile is in fact as important as the ability to create it by merging tiles of the same value.
The monotonicity of the row/column enforces generally good position for building up higher and higher tiles. Look at the code for more details, it's pretty self-explanatory. The calculation uses third powers of tile values, so that higher tiles get more severe penalty if they are moved in the middle of the board.

**Adaptive search depth limit**

This gives a huge speed boost, especially early in the game. The idea is that you need to search the game tree really deep only if the board gets complicated. A good measure of the board complexity is the number of distinct tiles. With this patch AI alternates between extremely fast segments (right after it builds a new highest tile) and slow segments (right before it builds a new highest tile).
I've measured a time it took to get to a certain tile for the original algorithm and the new one, here is how much time this patch saves:
 2k: 50%
 4k: 45%
 8k: 30%
16k:  5%
As you can see, the time to reach winning 2k tile was cut in half and it stays faster roughly up to a point when it builds 16k tile.

**Benchmark results**

(for final results see the last post)

There is ceratinly a room for tweaking the code, but I doubt it will be possible to get another significant improvement while keeping the computational cost at a sane level.

### CODE REVIEW

**Comment by tnmichael309** [comment]
We've used MS-TD learning and TD(lambda) to improve our 2048 AI.

The performance, source codes and papers references can be found here:
https://github.com/CGI-LAB/Taiwan_Bot_Tournament_2048
https://github.com/tnmichael309/2048AI

though codes are ugly....

we can have performance around
Average	        446116
Max	                833300
32768 rate	33.5%
Speed	        500 moves/sec

similar to the results with a slightly better avg/max/32768 rate, but large speed boost.

**Comment by nneonneo** [comment]
That's very impressive! Clearly the heuristics are very strong.

How well can it perform with deeper searching? If you make it work harder (maybe to 20 moves/sec) then can it get to 65536 sometimes?

**Comment by nneonneo** [comment]
Also, I see that there was a Threes! bot developed. I wonder if my threes bot (https://github.com/nneonneo/threes-ai) would have performed better or not. It is based on the same kind of deep search + heuristic approach, plus a bit of heuristic optimization with CMA-ES.

**Comment by tnmichael309** [comment]
Hi, @nneonneo 

Well, the bot for threes we developed did not further trained with TD(lambda)., but still trained with ms-td learning we proposed on TAAI. (Papers on Springer:  http://download-v2.springer.com/static/pdf/229/chp%253A10.1007%252F978-3-319-13987-6_34.pdf?token2=exp=1432349702~acl=%2Fstatic%2Fpdf%2F229%2Fchp%25253A10.1007%25252F978-3-319-13987-6_34.pdf*~hmac=a1b5d1ef89c00ffbfdecc464bf9f5a3e82d53c420b4961a10b41242991e48a7c)

current result for threes (the source code is not updated yet)
Reaching rate	         1-ply	2-ply	        3-ply (Search depth)
1536	                 28.4%	93.8%	97.4%
3072	                 0.8%	48.5%	65.8%
6144	                 0.0%	1.0%	9.0%
Maximum score	 207096	709,341	771,108
Average score	         35,763	158,151	221,326
Speed (moves/sec)	  21,537	14,099	298

For 2048, we run 10 thousands of games,
using 3-ply expectimax search (actually: play -> rand -> play -> rand -> play -> leaf, 2.5-ply...)
and we can have one 65536-tile(The score was 1064160)

Yet since I used bitboard with 'f' representing 32768,
I did not have much time to make further revision for it to show 65536. 
and I did not run deeper search.

If we want to have 32768-tile, we should keep adding more stages to MS-TD learning to have 65536-tile(as mentioned in the paper), and then we can try to have deeper search.

Thank you.

**Comment by nneonneo** [comment]
I just used the trick of having F+F=F in my AI, so that if two 32768 are
touching, it merges them.

Very cool that you got 65536. That's a big achievement.

**Comment by tnmichael309** [comment]
We've put our AI on the website: http://2048.aigames.nctu.edu.tw/

This is the record of 65536.


And thanks for the trick sharing :)

**Pull request merged**
